# DATABASE
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# HIKARI
spring.datasource.hikari.auto-commit=true
spring.jpa.properties.hibernate.connection.autocommit=true

# LOGGING
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# SERVER PORT
server.port=${PORT:8080}

# CUSTOM URLS
frontend.url=https://iraiviteahouse.netlify.app
backend.url=https://iraiviteahousebackend-production.up.railway.app
